version: "3"
name: "incarn-compose"
services:
  bot:
    image: incarn
    depends_on:
      - "database"
    env_file: ".env"

  database:
    image: postgres
    restart: "always"
    env_file: ".env"
